// export type RessourceStatus = "published" | "pending" | "refused" | "draft";

// export type Ressource = {
//   id: number;
//   title: string;
//   description?: string;
//   content: string;
//   tags?: string;
//   publication_date: string;
//   validation_date?: string | null;
//   is_validated: boolean;
//   status: RessourceStatus;

//   category_id: number;
//   user_id: number;
//   validator_id?: number | null;
//   type_ressource_id?: number | null;

//   upvotes?: number;
//   downvotes?: number;

//   user: {
//     id: number;
//     name: string;
//   };
//   validator?: {
//     id: number;
//     name: string;
//   };
//   category?: {
//     id: number;
//     name: string;
//   };
//   type?: {
//     id: number;
//     name: string;
//   };
// };
